### ISSUE TITLE
config file not used

### ISSUE THREAD

**Issue by M3CHR0M4NC3R** [cdown/zcfan#19] opened 2023-06-11 18:01 UTC
I have placed a config file at the path specified in the manpage, but the fan does not increase/decrease at my specified intervals. If it check the systemd process, it seems to be using the default temperature trip points.

**Comment by Pyntux** [comment] 2023-06-11 21:07
Same for me on Arch Linux on Linux 6.3.7-arch1-1. My setup is:

max_temp 85
med_temp 70
low_temp 56

but, fan is active even on 35c....

**Comment by M3CHR0M4NC3R** [comment] 2023-06-11 21:27
My temperatures are reading properly, odd

**Comment by cdown** [comment] 2023-06-12 04:43
Could you please show your config file location and contents? I can't reproduce -- it works here:

```
zcfan % cat /etc/zcfan.conf
max_temp 97
med_temp 90
low_temp 90
zcfan % sudo ./zcfan
[CFG] At 97C fan is set to maximum
[CFG] At 90C fan is set to medium
[CFG] At 90C fan is set to low
[FAN] Temperature now 44C, fan set to off
```

As for which temperature is used, zcfan uses all available sensors from sysfs and picks the highest. You can see which ones it might choose from with:

```
paste <(for label in /sys/class/hwmon/hwmon*/temp*_label; do cat "${label%/*}/name"; done) <(cat /sys/class/hwmon/hwmon*/temp*_label) <(cat /sys/class/hwmon/hwmon*/temp*_input) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'
```

**Comment by Pyntux** [comment] 2023-06-12 06:00
My confgi location is:

/etc/zcfan.conf

in config is only:

 max_temp 85
 med_temp 70
 low_temp   56

P.S. Everythin was working until kernel update... There is also problem with thinkfan after that update:
https://bbs.archlinux.org/viewtopic.php?id=282817

**Comment by rehanzo** [comment] 2023-07-06 23:38
Yea, seems the temp is being read wrong on mine as well. The max temperature doesn't match with what the program says.

**Comment by cdown** [comment] 2023-08-24 13:24
I'm going to close this since there was no update. This issue ended up covering a bunch of different things, feel free to refile if there is still something present. :-)

**Closed by cdown** 2023-08-24 13:24 UTC
